#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
#+ displays bad luck for the 4th loop iteration
#+ displays good luck for the 8th loop iteration
#+ displays Best School for the other iterations

num=0
while [ $num -lt 10 ]
do
	((num++))
	if [ $num -eq 4 ]; then
		echo "bad luck"
	elif [ $num -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
