#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# use the for loop
# Do not display hidden files

for files in *
do
	echo "$files" | cut -d "-" -f2
done
